### ISSUE TITLE
Accept input file through command line

### ISSUE THREAD

**Issue by gnawux** [teawater/gps2video#3]
currently the input file was written in config file, which make it hard to batch processing or input through pipe. I think it might help if we could specify input (and output) files in command line.

**Comment by teawater** [comment]
Good idea!
Add it to TODO to fix the issue.  :)

**Comment by larrycai** [comment]
@gnawux I also added this in my docker.md for todo list as well.

**Comment by teawater** [comment]
I am working on make the options part more flexible and powerful in branch opt.

**Comment by teawater** [comment]
Fixed in master.
